# https://github.com/tilt-dev/ctlptl/blob/main/pkg/api/types.go

# Create registry with pre-determined port
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
# Creates a kind cluster with Kind's custom cluster config
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kubernetesVersion: v1.22.1
# https://pkg.go.dev/sigs.k8s.io/kind/pkg/apis/config/v1alpha4#Cluster
kindV1Alpha4Cluster:
  name: nri-k8s-dev
  nodes:
  - role: control-plane
  # Add extra node to the cluster. 
  # - role: worker